add missing closing brace }
brunch --build production was errorring out on this line: 

error: --------------------------------------------------------------------------
error: An uncaught YUIDoc error has occurred, stack trace given below
error: --------------------------------------------------------------------------
error: 
Error: Parse error on line 2:
...    <h1>{{{fileName}} <small>File</smal
----------------------^
Expecting 'CLOSE_UNESCAPED', got 'CLOSE'
    at Object.e.parseError (/usr/local/lib/node_modules/yuidocjs/node_modules/yui/handlebars-compiler/handlebars-compiler-min.js:7:2149)
    at Object.e.parse (/usr/local/lib/node_modules/yuidocjs/node_modules/yui/handlebars-compiler/handlebars-compiler-min.js:7:3292)
    at Object.n.parse (/usr/local/lib/node_modules/yuidocjs/node_modules/yui/handlebars-compiler/handlebars-compiler-min.js:8:4025)
    at o (/usr/local/lib/node_modules/yuidocjs/node_modules/yui/handlebars-compiler/handlebars-compiler-min.js:11:4213)
    at Object.files (/usr/local/lib/node_modules/yuidocjs/node_modules/yui/handlebars-compiler/handlebars-compiler-min.js:11:4543)
    at Object.n.VM.invokePartial (/usr/local/lib/node_modules/yuidocjs/node_modules/yui/handlebars-base/handlebars-base-min.js:6:4603)
    at Object.eval (eval at <anonymous> (/usr/local/lib/node_modules/yuidocjs/node_modules/yui/handlebars-compiler/handlebars-compiler-min.js:10:1494), <anonymous>:7:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/yuidocjs/node_modules/yui/handlebars-base/handlebars-base-min.js:6:3397)
    at Object.layout_content (/usr/local/lib/node_modules/yuidocjs/node_modules/yui/handlebars-compiler/handlebars-compiler-min.js:11:4550)
    at Object.n.VM.invokePartial (/usr/local/lib/node_modules/yuidocjs/node_modules/yui/handlebars-base/handlebars-base-min.js:6:4603)
error: --------------------------------------------------------------------------
error: Node.js version: v0.10.20
error: YUI version: 3.14.1
error: YUIDoc version: 0.3.50
error: Please file all tickets here: http://github.com/yui/yuidoc/issues
error: --------------------------------------------------------------------------